---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx
      - david-tomson

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx
      - david-tomson

  - package-ecosystem: "npm"
    directory: "/packages/botway.js"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx
      - david-tomson

  - package-ecosystem: "pip"
    directory: "/packages/botway.py"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx
      - david-tomson

  - package-ecosystem: "pip"
    directory: "/tools/templates/discord/python/assets/pip"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx

  - package-ecosystem: "pip"
    directory: "/tools/templates/slack/python/assets/pip"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx

  - package-ecosystem: "pip"
    directory: "/tools/templates/telegram/python/assets/pip"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx

  - package-ecosystem: "cargo"
    directory: "/packages/botway-rs"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx
      - david-tomson

  - package-ecosystem: "cargo"
    directory: "/installer"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx

  - package-ecosystem: "cargo"
    directory: "/tools/templates/discord/rust/assets"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx
      - david-tomson

  - package-ecosystem: "cargo"
    directory: "/tools/templates/telegram/rust/assets"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx
      - david-tomson

  - package-ecosystem: "bundler"
    directory: "/packages/botwayrb"
    schedule:
      interval: "daily"
    reviewers:
      - abdfnx
