image:
  file: .gitpod/Dockerfile

tasks:
  - name: Setup Botway
    init: gomo
    command: gomo update
  
  - name: Setup Botway UI
    init: pnpm i
    command: pnpm start

ports:
  - port: 3000
    onOpen: open-browser
    name: Botway UI
    description: Botway UI Preview
