name: botway_dart
description: Dart client package for Botway.
version: 0.1.0
homepage: https://github.com/abdfnx/botway

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  path: ^1.8.2
  yaml: ^3.1.1
